document.getElementById("myButton").addEventListener("click", myFunction);

function myFunction (){
var quote = ["Smile, it's free therapy.", "Man will never be free until the last king is strangled with the entrails of the last priest.", "To forgive is to set a prisoner free and discover that the prisoner was you.", "If you love someone, set them free. If they come back they're yours; if they don't they never were.", "The truth will set you free, but first it will make you miserable.", "Software is like sex: it's better when it's free.", "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.", "When we lose the right to be different, we lose the privilege to be free.", "None are more hopelessly enslaved than those who falsely believe they are free.", "The four characteristics of humanism are curiosity, a free mind, belief in good taste, and belief in the human race.", "Throw off your worries when you throw off your clothes at night.", "Common looking people are the best in the world, that is the reason the Lord makes so many of them.", "The less one has to do, the less time one finds to do it in.", "The mind is not a vessel to be filled but a fire to be kindled.", "Friendship is a single soul dwelling in two bodies.", "Be yourself; everyone else is already taken.", "He who opens a school door, closes a prison.", "Love inspires, illuminates, designates and leads the way.", "For every minute you are angry you lose sixty seconds of happiness.", "Reading is to the mind what exercise is to the body.", "I am not afraid; I was born to do this.", "A superior man is modest in his speech, but exceeds in his actions.", "Without music, life would be a mistake.", "All great ideas are dangerous.", "The noblest pleasure is the joy of understanding.", "I can calculate the motion of heavenly bodies, but not the madness of people.", "Happiness is when what you think, what you say, and what you do are in harmony.", "You must be wise, but not too wise.", "He who has conquered doubt and fear has conquered failure.", "The most useless are those who never change through the years."]

var author = ["Douglas Horton", "Denis Diderot", "Lewis B. Smedes", "Richard Bach", "James A. Garfield", "Linus Torvalds", "Albert Camus", "Charles Evans Hughes", "Johann Wolfgang von Goethe", "E. M. Forster", "Napoleon Bonaparte", "Thomas Jefferson", "Abraham Lincoln", "Lord Chesterfield", "Plutarch", "Aristotle", "Oscar Wilde", "Victor Hugo", "Mary Baker Eddy", "Ralph Waldo Emerson", "Joseph Addison", "Joan of Arc", "Confucius", "Friedrich Nietzsche", "Oscar Wilde", "Leonardo da Vinci", "Isaac Newton", "Mahatma Gandhi", "Alexander T. Stewart", "James Lane Allen", "James M. Barrie"]

var today = new Date();
var dd = String(today.getDate()).padStart(2, '0');
document.getElementById("quote").innerHTML = quote[dd]
document.getElementById("author").innerHTML = "By: " + author[dd]

}